import type { Metadata } from "next";
import "./../globals.css";
import Header from "@/components/customerApp/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" >
      <body className="bg-slate-100 text-zinc-600 container mx-auto ">
        <Header/>
        <main className=" w-full ">{children}</main>
      </body>
    </html>
  );
}
