import type { Metadata } from "next";
import "./../globals.css";
import Header from "@/components/customerApp/Header";
import BottomMenu from "@/components/customerApp/BottomMenu";
import OrderCardProvider from "@/context/order-card";
import TotalCountOrdersProvider from "@/context/TotalCountOrders";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl">
      <body className="bg-slate-100 h-screen  text-zinc-600 container mx-auto overflow-hidden ">
        <OrderCardProvider>
          <TotalCountOrdersProvider>
            <Header />
            <main className=" w-full h-screen">{children}</main>
            <BottomMenu />
          </TotalCountOrdersProvider>
        </OrderCardProvider>
      </body>
    </html>
  );
}
