import type { Metadata } from "next";
import "./../globals.css";
import Header from "@/components/customerSite/Header";
import ReactQueryProvider from "@/components/providers/ReactQueryProvider";
import ToastifyContainer from "@/components/providers/TostifyContainer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="en">
      <body className="bg-slate-100 text-zinc-600">
        <ReactQueryProvider>
          <Header />
          <main>{children}</main>
        </ReactQueryProvider>
        <ToastifyContainer />
      </body>
    </html>
  );
}
